### ISSUE TITLE
Using node-oauth?

### ISSUE THREAD

**Issue by eklem** [interactivethings/gsheets#1]
Hi, I know it's defined as a non-feature, but how difficult do you think it would it be to connect to a non-published Google Drive Spreadsheet through `node-oauth`?
https://github.com/ciaranj/node-oauth/

**Comment by herrstucki** [comment]
If OAuth is really all that's needed than it shouldn't be too difficult to switch out Axios for something like node-oauth. But I don't really have the time to investigate at the moment. Feel free to fork and try out though :smile:. If you see an opportunity to modularize the data fetching, so it's easy for end-users to change the connection method, that would be even nicer.

In order to keep the current functionality it would be nice if such a solution would also work in the browser.

**Comment by eklem** [comment]
Thanks for a good answer, and a very nice module @herrstucki . I'm fairly new at JavaScript and Node.js, but I may have a go at it soon.
